#!/bin/bash

PHP_EXEC="docker-compose exec php php artisan"

print_usage() {
    echo "Usage:"
    echo "  migrate"
    echo "  page_view"
    echo "  page_list"
    echo "  page_remove"
}

migrate ()
{
    $PHP_EXEC migrate
}

page_view()
{
    $PHP_EXEC page:view $1
}

page_list()
{
    $PHP_EXEC page:list
}

page_remove()
{
    $PHP_EXEC page:remove $1
}

default()
{
    $PHP_EXEC $1
}

case "$1" in
    'migrate')
        migrate
        ;;

    'page_view')
        page_view $2
    ;;

    'page_list')
        page_list
    ;;

    'page_remove')
        page_remove $2
    ;;

    *)
        default $2
    ;;
esac
