version: "3"

services:
  php:
    build:
      context: docker-config/php
    volumes:
        - ./:/var/www
    working_dir: /var/www/code
    environment:
      DB_PORT: 3306
      DB_HOST: db
      PHP_IDE_CONFIG: serverName=dockerlaravel
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./:/var/www
        - ./docker-config/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    build:
      context: docker-config/db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

volumes:
  dbdata: